[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
startup_mode = "Maximized"

opacity = 0.8
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 20


