tap "homebrew/bundle"
brew "eza"
brew "git"
brew "neovim"
brew "powerlevel10k"
brew "tmux"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "node" # sorry
cask "alacritty"
cask "font-meslo-lg-nerd-font"
cask "keepassxc"
cask "librewolf"
